// Mocks generated by Mockito 5.4.6 from annotations
// in japan_post_api_client/test/japan_post_api_client_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:japan_post_api_client/japan_post_api_client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTokenApi_0 extends _i1.SmartFake implements _i2.TokenApi {
  _FakeTokenApi_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchcodeApi_1 extends _i1.SmartFake implements _i2.SearchcodeApi {
  _FakeSearchcodeApi_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddresszipApi_2 extends _i1.SmartFake implements _i2.AddresszipApi {
  _FakeAddresszipApi_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClientFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClientFactory extends _i1.Mock implements _i2.ApiClientFactory {
  @override
  _i2.TokenApi createTokeApi(_i2.ApiClient? apiClient) =>
      (super.noSuchMethod(
            Invocation.method(#createTokeApi, [apiClient]),
            returnValue: _FakeTokenApi_0(
              this,
              Invocation.method(#createTokeApi, [apiClient]),
            ),
            returnValueForMissingStub: _FakeTokenApi_0(
              this,
              Invocation.method(#createTokeApi, [apiClient]),
            ),
          )
          as _i2.TokenApi);

  @override
  _i2.SearchcodeApi createSearchcodeApi(_i2.ApiClient? apiClient) =>
      (super.noSuchMethod(
            Invocation.method(#createSearchcodeApi, [apiClient]),
            returnValue: _FakeSearchcodeApi_1(
              this,
              Invocation.method(#createSearchcodeApi, [apiClient]),
            ),
            returnValueForMissingStub: _FakeSearchcodeApi_1(
              this,
              Invocation.method(#createSearchcodeApi, [apiClient]),
            ),
          )
          as _i2.SearchcodeApi);

  @override
  _i2.AddresszipApi createAddresszipApi(_i2.ApiClient? apiClient) =>
      (super.noSuchMethod(
            Invocation.method(#createAddresszipApi, [apiClient]),
            returnValue: _FakeAddresszipApi_2(
              this,
              Invocation.method(#createAddresszipApi, [apiClient]),
            ),
            returnValueForMissingStub: _FakeAddresszipApi_2(
              this,
              Invocation.method(#createAddresszipApi, [apiClient]),
            ),
          )
          as _i2.AddresszipApi);
}
